spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zusa_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

app:
  upload:
    base-path: /Users/jaaason30/Desktop/react_start_project/backend/uploads
    base-url: /static/uploads
    max-size-bytes: 104857600  # 100MB for video files
    allowed-types: "image/jpeg,image/png,image/webp,image/gif,video/mp4,video/quicktime,video/x-msvideo"

  post:
    official-emails: "admin@zusa.io,editor@zusa.io"
    max-images: 9

jwt:
  secret: mySecretKey_ThisShouldBeAtLeast256BitsLongForHS256Algorithm_ChangeInProduction
  expiration: 3600000       # 1小时 (毫秒)
  refresh:
    expiration: 604800000   # 7天 (毫秒)

logging:
  level:
    root: info
    com.zusa: debug
